### PR TITLE
random - randomly blink lights

### PR DESCRIPTION
**Pull request by thapakazi**
This will make blinking more fun.

Get random number upto 200ms.

Watch out Code could be buggy :D @WinnerBishal

### CODE REVIEW

**Comment by WinnerBishal** [comment]
bro,u missed to make change in loop...it may not work still.

**Comment by thapakazi** [comment]
Ok, I will send the patches. hold on tight :grinning:

**Comment by thapakazi** [comment]
oh no, I closed the thread :man_facepalming:  
I will reopen with this comment though :D

**Comment by WinnerBishal** [comment]
yaa,yaa

**Pull request merged**
